### PR TITLE
Mavenize.

### PR DESCRIPTION
**Pull request by drtshock**
Makes the project super nice and easy. Can easily compile by cloning then doing `mvn clean package` in command line (with maven installed).

Adds https://github.com/tastybento/askyblock/issues/13

### CODE REVIEW

**Comment by drtshock** [comment]
Any comments on this? Would love to see it pulled.

**Comment by tastybento** [comment]
Thanks a lot! I've been super busy this week so I'll look at it this weekend!

**Comment by drtshock** [comment]
yayyayyayayayayayay

**Comment by lol768** [comment]
:grinning:

**Comment by tastybento** [comment]
I had to make some changes to it so look in 2.9.1 for what I did. One was that the schematic file is a binary so needs protecting from UTF-8 encoding.

**Pull request merged**
