### PR TITLE
Add Sky Factory schematic

### PR DESCRIPTION
**Pull request by martmists**
Add a schematic for servers running the Sky Factory modpack

### CODE REVIEW

**Comment by tastybento** [comment]
Can you give some more background as to why this should be part of the mainline? I don't know about sky factory so I'm not sure what this schematic does or why it is needed. Thanks.

**Comment by Jack-McKalling** [comment]
For reference, Sky Factory is a modpack made by a livestreamer called [Bacon Donut](http://twitch.tv/bacon_donut). You can watch Ssundee as he plays through three series with the modpack:
[Minecraft Modded SkyFactory 1](https://www.youtube.com/watch?v=2ZOvJd5ckDw) (30 eps)
[Minecraft SkyFactory 2](https://www.youtube.com/watch?v=fUyOZRPXylA) (35 eps)
[Minecraft: SkyFactory 3](https://www.youtube.com/watch?v=UkNUnmrXUuc) (19 eps, ongoing)

**Comment by tastybento** [comment]
Okay, understood on that. Can you give some instructions on how to set up a sky factory server with AKyBlock and this schematic because I'd like to add it to the wiki if this schematic is included in the main build.

**Comment by martmists** [comment]
Sky Factory is kinda what you would call a modded skyblock. It comes with a
different map since the mechanics are a lot different. The reason I wanted
to add this is because I've had quite the struggle figuring out how to make
it work, but I don't deem it completely necessary.

**Comment by martmists** [comment]
Step 1: Get a sky factory server (ATLauncher recommended)
Step 2: Get Thermos (note to self: add link) to use plugins as well
Step 3: Add ASkyBlock
Step 4: Only allow the SkyFactory schematic in config.yml

**Comment by martmists** [comment]
Step 1: Get a sky factory server ([ATLauncher](https://www.atlauncher.com/downloads) recommended)
Step 2: Get [Thermos](https://github.com/CyberdyneCC/Thermos) to use plugins as well
Step 3: Add ASkyBlock
Step 4: Only allow the SkyFactory schematic in config.yml

**Comment by tastybento** [comment]
Thanks, I'll check it this weekend.

**Comment by tastybento** [comment]
@martmists : I'm having trouble getting Thermos to work with SkyFactory 2 - it crashes out every time. Can you try it and see if it works for you, or if there's a trick to getting it to work? Here's what I did:

1. Clicked on the Sky Factory 2 Server download in AT Launcher (version 24)
2. Went to the server folder, deleted libraries folder
3. Copied in the Thermos jar (latest from Github) and the new libraries folder and created a run script
4. Ran the server. It gets quite far, but always crashes out with the same error:

cpw.mods.fml.common.LoaderException: java.lang.VerifyError: Bad local variable type

Thanks!

**Comment by martmists** [comment]
Hmm, it works on my end though. If you want to see a live version, try `martmists.tk` as IP since it works there

**Comment by tastybento** [comment]
I'm just trying to get tbe install instructions right so I can tell the users. I'll try it on another server. If my instructions should work, I'll try and work out why it isn't working.

**Comment by aycgit** [comment]
What would possibly be cool is that if the plugins detects skyfactory, it then allows people to choose that island type

**Comment by evernife** [comment]
Why not just be able to choose the schematic?

> 1- Upload the schematic to the config foder
> 2- Change the name in the config 
> image

or something like that :D

**Pull request closed without merging**
