### PR TITLE
Code clean and misc

### PR DESCRIPTION
**Pull request by vellde**

### CODE REVIEW

**Comment by UnioDex** [comment]
Hi @vellde what is the reason you changed some of HashMaps to Maps? I googled the difference betwwen HashMap and Map and it says Map is an abstract class and HashMap is it's implementation. It didn't says me when to use Map and when to use HashMap.

**Comment by tastybento** [comment]
Thanks. The code badly needed this. I’ll review and merge after that. 

@uniodex The Map thing is correct. You declare map, but implement hashmap.

**Comment by tastybento** [comment]
@vellde Thanks. Did you use a code analysis tool to generate the changes? If so, which one did you use?

**Comment by DuckSoft** [comment]
Maybe **IntelliJ IDEA Ultimate**, I think.

**Comment by vellde** [comment]
@DuckSoft yep

**Pull request merged**
