### PR TITLE
Add tab completion to all commands.

### PR DESCRIPTION
**Pull request by Pokechu22**
This adds tab completion to all of the current commands, along with making a few changes to simplify tab completion.  Tab-completion includes permission checking as well.

### CODE REVIEW

**Comment by tastybento** [comment]
I like this! Let me play with it a bit more.

**Comment by tastybento** [comment]
Looks good. BTW, make is a private command that shouldn't ever need to be used or available for a player, so I'll remove that option from the code.

**Comment by Pokechu22** [comment]
Looks good!

Although (and this is rather unrelated to the pull request) it seems like you've changed your email or something because your new commits (such as de63ee9) aren't being associated with your github account.  

What it looked like on d96dfe9: 
d96dfe9's commit, with tastybento's icon and a link to the github profile

What it looks like on de63ee9: 
de63ee9's commit, showing the plain text "tastybento" (no link) and the default github icon

If you did change it you'll probably want to follow the steps shown [here](https://help.github.com/articles/adding-an-email-address-to-your-github-account/) (and optionally, [here](https://help.github.com/articles/changing-your-primary-email-address/)) to associate the new email with your account.

**Comment by tastybento** [comment]
Thanks for the tip - yes I did change email. Fixed now!

**Pull request merged**
