### PR TITLE
Monster Eggs

### PR DESCRIPTION
**Pull request by Steev93**
Spawn Eggs,

How do we add them as Icons like Rabbit Eggs as Icon Challenges or even add Eggs in the minishop i've tried from SPAWN_EGG to MONSTER_EGG with :101 and more. Just need assistants now! 

Thanks

### CODE REVIEW

**Comment by tastybento** [comment]
https://github.com/tastybento/askyblock/wiki/Frequently-Asked-Questions#monsterspawn-eggs-dont-work-any-more

**Comment by Steev93** [comment]
Thanks! did not see this

**Comment by Steev93** [comment]
Challenges: http://prntscr.com/bqzff4
Config: http://prntscr.com/bqzfi0

I've tried that or can you just not do it as icons ?

**Comment by tastybento** [comment]
Ah, yes you cannot with that version. I added it in the latest unreleased version here:
https://github.com/tastybento/askyblock/releases/tag/3.0.1.2

**Comment by Steev93** [comment]
Thanks! i will do this update tonight that is what i have been trying to do :)

**Pull request closed without merging**
