### PR TITLE
Fix NL translations

### PR DESCRIPTION
**Pull request by aycgit**
Happy i could help :)

### CODE REVIEW

**Comment by tastybento** [comment]
Thanks!

**Comment by Jack-McKalling** [comment]
I added two small notes/suggestions to the translations, as I'm also a Dutch translator. But I don't currently have a repository set up to fix it myself. Would you like to do it @aycgit ?

**Comment by aycgit** [comment]
@jack-mckalling yes, i will fix them when im back on my pc

**Comment by Jack-McKalling** [comment]
Great :smile:

**Pull request merged**
