### PR TITLE
Animal breeding and monster limit

### PR DESCRIPTION
**Pull request by Poslovitch**
https://github.com/tastybento/askyblock/issues/164
https://github.com/tastybento/askyblock/issues/425
https://github.com/tastybento/askyblock/issues/226

I started work on this three suggestions, but I need some help about IslandGuard : I couldnt find a proper way to "limit" animal & monster spawn with these new settings.

Off topic : can you please close done issues for 3.0.6? I'd like to see more easily what remains.

### CODE REVIEW

**Comment by tastybento** [comment]
Okay, I closed some issues. If you see some still open that need closing, leave a comment.

I will look through this PR in the next day or so.

**Comment by tastybento** [comment]
I recommend that instead of using individual Settings.xxx variables, you use a HashMap<EntityType, Integer> monsterLimits

Then fill the hashmap from the config. You could also possibly load in the config as a StringList, so the YAML would be like this:

monsterlimits:
- CREEPER:3
- ZOMBIE:10
- SPIDER:5

etc.

However, having said all this, there is a one problem: how to count all the entities on all the islands. 

Method 1: Plugin tries to keep count
Do a check of the creature count on an island every time a creature is spawned.  One event listener:
CreatureSpawnEvent: find out where creature spawned, count all the creatures on that island, check if it is > limit. If not, allow spawn, otherwise cancel.

Method 2: Better idea???

**Comment by Poslovitch** [comment]
It all looks good.

Indeed, method 1 would really use a lot of resources.
I thought we should "store" the amount of creatures that are on the island. Just increase or decrease. Maybe more complex to setup, but more efficient?

**Comment by tastybento** [comment]
@Poslovitch Unfortunately, getting that to work across server restarts is hard (the data has to be saved) and it can get out of sync really easily. The best approach is to use the server itself and I've got an idea to tag entities when they are created. Let me do some investigation.

**Comment by tastybento** [comment]
Check out 49b13ed. I think this does it generally. Also, it should be easy to add the /is limits command because each entity is now tagged with the spawn island center location.

**Comment by Poslovitch** [comment]
This commit looks good. I will work on /is limits in an other pr.

**Pull request closed without merging**
