### PR TITLE
rearrangement

### PR DESCRIPTION
**Pull request by wolfwork**
Personally, I think this is good

### CODE REVIEW

**Comment by drtshock** [comment]
While I can agree that a reformat would be nice, your commit history here is :(

**Comment by wolfwork** [comment]
That does not matter...

**Comment by drtshock** [comment]
It should. Clean commit history should be important to a project. Though it looks like bento likes to show branch merge commits among other things :(

**Comment by tastybento** [comment]
I do like branch merges :-)

I had a look at the pull request, but I can't tell what is actually changing. Is it just a reformatting? Like spacing and tabs and stuff?

**Comment by wolfwork** [comment]
just reformatting
No changing
Just.. i hope your code will more clearly

**Comment by tastybento** [comment]
Hmm. Well, it's not an auto-merge anymore so I can't accept the request this time.

**Pull request closed without merging**
