### PR TITLE
Mobspawning island setting

### PR DESCRIPTION
**Pull request by Poslovitch**

### CODE REVIEW

**Comment by tastybento** [comment]
I think the SettingsPanel class also needs some code to show the icon.

**Comment by Poslovitch** [comment]
It's already added.
`ip.add(new IPItem(Settings.allowMobSpawning, Material.MOB_SPAWNER, plugin.myLocale(uuid).igsMobSpawning));`

**Comment by Poslovitch** [comment]
Oh I see. The SettingsPanel file wasn't sent with this commit.

**Comment by tastybento** [comment]
Actually, as this changes config.yml, I should change the version to 3.0.5. That will be the new branch.

**Pull request merged**
