### PR TITLE
[WIP] Schematic import improvement

### PR DESCRIPTION
**Pull request by SpyL1nk**
Hi,

For my comunity, I needed to import more complete schematics with some "decorations" for example. When I saw I'm not alone to ask for that (http://dev.bukkit.org/bukkit-plugins/skyblock/tickets/458-better-schematics/) I started working on this. For now I only added features I needed but it's planned to improve this to handle every entities/tiles. For now I just worked on skulls block (fully completed and fully tested), flower pots (fully completed and fully tested), paintings (not fully tested so I'm not sure that paintings larger than 2x2 blocks spawn well ...), item frames (not fully implemented, I need to add some information about the item in the frame like enchantement, name, lore etc.). I also fixed a little mistake in your code, yaw and pitch were reversed wich caused some issues with armor stands rotation.

I'm not a Java export and even less an Bukkit Plugin expert (it's one of the first plugin I work on) so I pretty sure my code can be improved then just correct it :)

SpyL1nk from Just2Craft team - just2craft.fr

### CODE REVIEW

**Comment by tastybento** [comment]
This is great work! Thanks!
The only thing I'll need to change is to have the nms (CraftWorld, etc.) functions kept in the NMS classes so that the plugin won't break when the server moves to 1.9 (which is going to happen really soon) or if the plugin is run on older server versions. From looking through the code, it looks like it's just a few methods that could be put into the NMS class. I could do it, but if you'd like to, that would be great. Let me know!

**Comment by SpyL1nk** [comment]
Thank, you :)
I'm sorry but it's the first time I use nms so I'm not comfortable with it, so I you can do it then you have time I will be great :D

**Comment by tastybento** [comment]
Thanks - I made a pull request to another branch and merged in from there.

**Comment by tastybento** [comment]
@SpyL1nk Thank for contributing to ASkyBlock! We are now doing a rewrite called BSkyBlock that will use the BSD License instead of the GPLv2 so I wanted your permission to use all your ASkyBlock contributions on BSkyBlock if we need them. If you agree please reply to this message with "I agree". If not, that's fine, we will avoid using your code. Thanks a lot!

**Pull request closed without merging**
