### PR TITLE
Updated dutch language

### PR DESCRIPTION
**Pull request by Dkamps18**

### CODE REVIEW

**Comment by Yuuki2012** [comment]
Few things are still wrongly translated... not really suggested to pull.

**Comment by Dkamps18** [comment]
What is wrongly translated?

**Comment by Dkamps18** [comment]
Corrected Thanks :) I must have looked over it

**Comment by Yuuki2012** [comment]
No problem, much better. ;)

**Comment by tastybento** [comment]
Thanks!

**Pull request merged**
