### PR TITLE
Toggle offline redstone

### PR DESCRIPTION
**Pull request by Poslovitch**
https://github.com/tastybento/askyblock/issues/309

### CODE REVIEW

**Comment by tastybento** [comment]
@Poslovitch - I was thinking - how about instead of it being based on whether a team member is on the island, instead it is just whether any player is on the island? In that case, it'll work for visitors as well.

**Comment by Poslovitch** [comment]
@Tastybento Hmmm... Yes it should work better and not cause problems.

**Comment by tastybento** [comment]
Okay, I'll add that.

**Comment by YellowZaki** [comment]
An option to disable for offline island members (like Poslovitch did), not only when anybody is in the island please. Because sometimes I have to disable redstone mechanisms that cause low fps (because of the void lighting bug).
About https://github.com/tastybento/askyblock/pull/385/commits/f88ee646ff3afef3fec3426f5c1199f73277b9b7
It is working for me but only for team members, not for leaders (when only the leader is connected to the island, the redstone doesnt work)

**Comment by tastybento** [comment]
Yes, actually I studied this and it is far more efficient to just do island members. I'll look at your bug report.

**Comment by tastybento** [comment]
@yellowzaki Oh you should try the latest 3.0.5 because I updated it alreafy.

**Comment by YellowZaki** [comment]
Right now bukkit web is migrating.
I compiled the Poslovitch code and I have watched that you haven't made any changes so it should work the same (only working for members, not when the island leader is alone in the island)
Sorry if I'm saying stupid things, it is the first time I have compiled something.

**Comment by tastybento** [comment]
Do a pull of the latest 3.0.5 so you get the latest commits. There are new changes in there.

**Comment by YellowZaki** [comment]
Now it is working fine.
The problem is that redstone clocks must be reactivate it on rejoin, but I suppose there is not a solution.
Anyway, this will reduce the lag a lot. Thanks!

**Pull request merged**
