### PR TITLE
Give Permissions when on island

### PR DESCRIPTION
**Pull request by Poslovitch**
https://github.com/tastybento/askyblock/issues/380

Functional, but may need some fixes for indentation.

### CODE REVIEW

**Comment by Poslovitch** [comment]
I just thought it'll need some minor tweaks (don't add perm if player already have, avoid the revoke of permissions players should have permanently...). I'll do them tomorrow ;)

**Comment by tastybento** [comment]
Looks good.

**Comment by tastybento** [comment]
I'll merge this in now because I'm working on some 3.0.6 functionality now. Feel free to do another pull request.

**Comment by Poslovitch** [comment]
Okay. I'll make an other pr to do these tweaks tomorrow, and I'll work on spacers( #443 ) wednesday.
Do we have a due date for 3.0.6? What is the functionnality you're talking about? @tastybento

**Pull request merged**
